SET LINESIZE 110
SET TERMOUT OFF
SET ECHO OFF
SET PAGESIZE 0
SET HEADING ON
SET FEEDBACK OFF
SET UNDERLINE OFF
SET TRIMSPOOL ON
SET TRIMOUT ON
SET VERIFY OFF
SET ARRAY 500
SET WRAP ON
SPOOL /home/bhemanth/DateEx/extraction.dsv
SELECT 'EMPNO;ENAME;JOB;MGR;HIREDATE;SAL;COMM;DEPTNO' FROM dual;
select EMPNO||';'||
ENAME||';'||
JOB||';'||
MGR||';'||
HIREDATE||';'||
SAL||';'||
COMM||';'||
DEPTNO
from emp;
SPOOL OFF
